name: Build

on:
  push:
    branches: [ dieeasy/action_test ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      NDK_VERSION: 20.1.5948944
      PKG_CONFIG_ALLOW_CROSS: 1
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpcre3-dev libssl-dev libzmq3-dev
          wget -nv https://freefr.dl.sourceforge.net/project/swig/swig/swig-4.0.1/swig-4.0.1.tar.gz
          tar xf swig-4.0.1.tar.gz
          cd swig-4.0.1 && ./configure && make -j4 && sudo make install
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --release
      - name: set environment variables
        run: |
          ANDROID_SDK_ROOT="$GITHUB_WORKSPACE/sdk"
          NDK_HOME="$ANDROID_SDK_ROOT/ndk/$NDK_VERSION"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "NDK_HOME=$NDK_HOME" >> $GITHUB_ENV
          echo "ANDROID_NDK_HOME=$NDK_HOME" >> $GITHUB_ENV
          echo "PATH=$PATH:$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin:$NDK_HOME/build/core/toolchains/" >> $GITHUB_ENV
          echo "CARGO_TARGET_AARCH64_LINUX_ANDROID_LINKER=$NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android26-clang" >> $GITHUB_ENV
      - name: Install NDK
        run: |
          wget -nv https://dl.google.com/android/repository/commandlinetools-linux-6609375_latest.zip
          unzip commandlinetools-linux-6609375_latest.zip
          mkdir $ANDROID_SDK_ROOT && mv tools $ANDROID_SDK_ROOT/
          yes 2>/dev/null | $ANDROID_SDK_ROOT/tools/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
            "platform-tools" "build-tools;29.0.3" "platforms;android-29" "ndk;$NDK_VERSION" "cmake;3.10.2.4988404" |grep -v '\[='; true
      - name: Add rust targets for android
        run: rustup target add aarch64-linux-android
      - name: set cross-build environment variables
        run: |
          echo "CC=aarch64-linux-android21-clang" >> $GITHUB_ENV
          echo "CFLAGS=--sysroot=$NDK_HOME/sysroot -I$NDK_HOME/sysroot/usr/include -I$NDK_HOME/sysroot/usr/include/aarch64-linux-android" >> $GITHUB_ENV
          echo "CXX=aarch64-linux-android21-clang++" >> $GITHUB_ENV
          echo "CXXFLAGS=$CFLAGS -nostdlib++ -I$NDK_HOME/sources/cxx-stl/llvm-libc++/include" >> $GITHUB_ENV
          echo "LDFLAGS=--sysroot=$NDK_HOME/platforms/android-21/arch-arm64" >> $GITHUB_ENV
      #- name: Build for android
      #  run: CC="aarch64-linux-android21-clang" CFLAGS="--sysroot=$NDK_HOME/sysroot -I$NDK_HOME/sysroot/usr/include -I$NDK_HOME/sysroot/usr/include/aarch64-linux-android" CXX="aarch64-linux-android21-clang++" CXXFLAGS="$CFLAGS -nostdlib++ -I$NDK_HOME/sources/cxx-stl/llvm-libc++/include" LDFLAGS="--sysroot=$NDK_HOME/platforms/android-21/arch-arm64" cargo build --all-features --release --target=aarch64-linux-android
      - name: Build for android
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --release --target=aarch64-linux-android
  ios:
    runs-on: macos-latest
    env:
      PKG_CONFIG_ALLOW_CROSS: 1
    steps:
      - uses: actions/checkout@v2
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install dependencies
        run: |
          brew install cmake openssl zmq
          rustup target add aarch64-apple-ios x86_64-apple-ios
          cargo install cargo-lipo
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: lipo
          args: --all-features --release
