name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          target: aarch64-linux-android
      - name: Install dependencies
        run: |
          sudo apt-get install -y libpcre3-dev libssl-dev libzmq3-dev
          wget https://freefr.dl.sourceforge.net/project/swig/swig/swig-4.0.1/swig-4.0.1.tar.gz
          tar xf swig-4.0.1.tar.gz
          cd swig-4.0.1 && ./configure && make -j4 && sudo make install
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=aarch64-linux-android
