name: Pre-publishing check

on:
  push:
    branches: [ dieeasy/publish ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v2
      - name: Install rust stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --dry-run
